import imgFirstSectionNovels1 from './1.webp';
import imgFirstSectionNovels2 from './2.webp';
import imgFirstSectionNovels3 from './3.webp';
import imgFirstSectionNovels4 from './4.webp';
import imgFirstSectionNovels5 from './5.webp';
import imgFirstSectionNovels6 from './6.webp';
import imgFirstSectionNovels7 from './7.webp';
import imgFirstSectionNovels8 from './8.webp';
import imgFirstSectionNovels9 from './9.webp';
import imgFirstSectionNovels10 from './10.webp';
import imgFirstSectionNovels11 from './11.webp';
import imgFirstSectionNovels12 from './12.webp';
import imgFirstSectionNovels13 from './13.webp';
import imgFirstSectionNovels14 from './14.webp';
import imgFirstSectionNovels15 from './15.webp';
import imgFirstSectionNovels16 from './16.webp';
import imgFirstSectionNovels17 from './17.webp';
import imgFirstSectionNovels18 from './18.webp';

export const imageFirstSectionNovels1 = imgFirstSectionNovels1;
export const imageFirstSectionNovels2 = imgFirstSectionNovels2;
export const imageFirstSectionNovels3 = imgFirstSectionNovels3;
export const imageFirstSectionNovels4 = imgFirstSectionNovels4;
export const imageFirstSectionNovels5 = imgFirstSectionNovels5;
export const imageFirstSectionNovels6 = imgFirstSectionNovels6;
export const imageFirstSectionNovels7 = imgFirstSectionNovels7;
export const imageFirstSectionNovels8 = imgFirstSectionNovels8;
export const imageFirstSectionNovels9 = imgFirstSectionNovels9;
export const imageFirstSectionNovels10 = imgFirstSectionNovels10;
export const imageFirstSectionNovels11 = imgFirstSectionNovels11;
export const imageFirstSectionNovels12 = imgFirstSectionNovels12;
export const imageFirstSectionNovels13 = imgFirstSectionNovels13;
export const imageFirstSectionNovels14 = imgFirstSectionNovels14;
export const imageFirstSectionNovels15 = imgFirstSectionNovels15;
export const imageFirstSectionNovels16 = imgFirstSectionNovels16;
export const imageFirstSectionNovels17 = imgFirstSectionNovels17;
export const imageFirstSectionNovels18 = imgFirstSectionNovels18;
