import imgFirstSectionBooks1 from './1.webp';
import imgFirstSectionBooks2 from './2.webp';
import imgFirstSectionBooks3 from './3.webp';
import imgFirstSectionBooks4 from './4.webp';
import imgFirstSectionBooks5 from './5.webp';
import imgFirstSectionBooks6 from './6.webp';
import imgFirstSectionBooks7 from './7.webp';
import imgFirstSectionBooks8 from './8.webp';
import imgFirstSectionBooks9 from './9.webp';
import imgFirstSectionBooks10 from './10.webp';
import imgFirstSectionBooks11 from './11.webp';
import imgFirstSectionBooks12 from './12.webp';
import imgFirstSectionBooks13 from './13.webp';
import imgFirstSectionBooks14 from './14.webp';
import imgFirstSectionBooks15 from './15.webp';
import imgFirstSectionBooks16 from './16.webp';
import imgFirstSectionBooks17 from './17.webp';
import imgFirstSectionBooks18 from './18.webp';

export const imageFirstSectionBooks1 = imgFirstSectionBooks1;
export const imageFirstSectionBooks2 = imgFirstSectionBooks2;
export const imageFirstSectionBooks3 = imgFirstSectionBooks3;
export const imageFirstSectionBooks4 = imgFirstSectionBooks4;
export const imageFirstSectionBooks5 = imgFirstSectionBooks5;
export const imageFirstSectionBooks6 = imgFirstSectionBooks6;
export const imageFirstSectionBooks7 = imgFirstSectionBooks7;
export const imageFirstSectionBooks8 = imgFirstSectionBooks8;
export const imageFirstSectionBooks9 = imgFirstSectionBooks9;
export const imageFirstSectionBooks10 = imgFirstSectionBooks10;
export const imageFirstSectionBooks11 = imgFirstSectionBooks11;
export const imageFirstSectionBooks12 = imgFirstSectionBooks12;
export const imageFirstSectionBooks13 = imgFirstSectionBooks13;
export const imageFirstSectionBooks14 = imgFirstSectionBooks14;
export const imageFirstSectionBooks15 = imgFirstSectionBooks15;
export const imageFirstSectionBooks16 = imgFirstSectionBooks16;
export const imageFirstSectionBooks17 = imgFirstSectionBooks17;
export const imageFirstSectionBooks18 = imgFirstSectionBooks18;
